### PR TITLE
Basic Linear Regression Implementation

### LINKED ISSUE #1: Demonstrate spark's mongo connector via linear regression model
An example of spark's mongodb connector needs to be implemented, tested, and demoed to demonstrate compatibility with sustain databases in mongodb.

### PR DESCRIPTION
**Pull request by inf0rmatiker**
This PR aims to introduce a basic linear regression example that runs Spark on DataFrames pulled in from `hospitals_geo` in our Sustain MongoDB.

Future issues will be created/implemented regarding the static nature of this code, and provide a more user-friendly interface for defining models.

Closes #1

### CODE REVIEW

**Comment by inf0rmatiker** [comment]
Oh, and the `target/` directory has been `.gitignore`d.

**Review by menuka94 — APPROVED** [review]

**Comment by kevin-bruhwiler** [comment]
Is there something in particular you want reviewed? There's a lot going on here, I don't know if it looks right, or even how to test it.

**Comment by inf0rmatiker** [comment]
> Is there something in particular you want reviewed? There's a lot going on here, I don't know if it looks right, or even how to test it.

No, nothing in particular.
I had tested it by running it in a spark-shell, but running it in a standalone spark app isn't working right now. I'm trying to figure out what's wrong but in the meantime I'm declining this PR.

**Comment by inf0rmatiker** [comment]
> Is there something in particular you want reviewed? There's a lot going on here, I don't know if it looks right, or even how to test it.

@kevin-bruhwiler 
To test it, you'll need to:

1. `ssh lattice-167`
2. `git clone https://github.com/Project-Sustain/sustain-spark-connector.git`
3. `cd sustain-spark-connector`
4. `git checkout feature/SSC-1`
5. `sbt clean`
6. `sbt compile`
7. `sbt run`

EDIT: Of course, this can all be found in the `README.md` of this branch as well.

**Review by kevin-bruhwiler — APPROVED** [review]

**Pull request merged**
